# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.PositiveSmallIntegerField()),
                ('posiciongps', models.CharField(max_length=200)),
                ('posiciongm', models.CharField(max_length=200)),
            ],
        ),
    ]
