# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustopapp', '0002_auto_20161227_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('posiciongm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustopapp.Gm')),
                ('posiciongps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustopapp.Gps')),
            ],
        ),
    ]
