# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustopapp', '0003_parada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='posiciongm',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='posiciongm',
        ),
        migrations.AlterField(
            model_name='bus',
            name='posiciongps',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='parada',
            name='posiciongps',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.DeleteModel(
            name='Gm',
        ),
        migrations.DeleteModel(
            name='Gps',
        ),
    ]
