# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustopapp', '0004_auto_20161228_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='posiciongps',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='posiciongps',
        ),
        migrations.AddField(
            model_name='bus',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parada',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parada',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
