# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustopapp', '0005_auto_20161228_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='numero',
            field=models.CharField(max_length=3),
        ),
    ]
