# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bustopapp', '0007_paradaseleccionada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paradaseleccionada',
        ),
    ]
