# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustopapp', '0008_delete_paradaseleccionada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustopapp.Linea'),
        ),
    ]
